Components and jsx
Mohamed-js/math-magicians pull request #3
Opened 2021-04-22 04:44 UTC by Mohamed-js

Added Display, Button, and ButtonPanel components.
Filled them with the necessary JSX code.

2021-04-22 12:13 UTC, Torres-ssf requested changes
### Changes Required :muscle: 
Hi @Mohamed-js :hand: 
Awesome job on this milestone so far :clap: 
But we need to make some changes before moving on.

- [ ] We need to update the README file by adding descriptive information about the project. Right now the README lacks relevant information about the project since it still has the placeholder text generated by `create-react-app`.
	![Screenshot from 2021-02-03 13-37-02](https://user-images.githubusercontent.com/30977845/106778665-f8906300-6624-11eb-9672-7ca6cff8dde8.png)

Happy coding :computer: 
**Sérgio Torres**

2021-04-22 12:13 UTC, Torres-ssf commented on .eslintrc.json
> +}
- [ ] This file is different from the one provided by Microverse. We should use [this version](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json) instead.

- [ ] The linter was not properly set up in the repository. We need to add all related linter dependencies as devDependecies. We need to follow the instructions [here](https://github.com/microverseinc/linters-config/tree/master/react-redux) at the Eslint section.

2021-04-22 12:13 UTC, Torres-ssf commented on src/components/App.js
> +      /* name: 'hay' */
- [ ] We can remove this commented code here.

2021-04-22 12:13 UTC, Torres-ssf commented on src/components/App.js
> +        <Display result="15" />
- [ ] Since at the Display component we are defining a default value for the result props, there is no need to pass a value for it right now.

2021-04-22 12:13 UTC, Torres-ssf commented on src/components/ButtonPanel.js
> +};
- [ ] ButtonPanel component does not receive any props for now, so there is no need to declare proptypes for it.

2021-04-23 05:35 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @Mohamed-js**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-04-24 03:49 UTC, merged